const express = require('express');
const router = express.Router();
const c = require('../controllers/paymentController');
const { authenticate } = require('../middleware/auth');
router.use(authenticate);
router.get('/', c.getAll);
router.get('/overdue', c.getOverdue);
router.post('/', c.create);
router.put('/:id', c.update);
router.delete('/:id', c.remove);
module.exports = router;
